name: Simple Bug Report
description: Report a simple bug or issue
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the information below to help us fix the issue.
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: "Describe the bug clearly and concisely"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to Reproduce
      description: Steps to reproduce this issue
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
